---
title: "Publications"
description-meta: "Published Papers"
#page-layout: full
#back-to-top-navigation: true
title-block-banner: false
css: custom.css
---


<!-- <!--Include academic icons or buttons--> 
<!-- {{< include /files/includes/_academic.qmd >}} -->

### 2025

**_Graf, D. R. M._**, Moser, M. K., Gandhi, S., Badici, M. & Resch, B. (2025). [A multimodal approach combining wearable sensors and point of view videos to evaluate stress in urban cycling.](https://doi.org/10.1145/3785480) *ACM Transactions on Spatial Algorithms and Systems*. \[[pdf](https://dl.acm.org/doi/pdf/10.1145/3785480)\]

<center><hr style="width:50%"></center>

Moser, M. K., Schmidt, S., **_Graf, D. R. M._**, Keskin, M., Gandhi, S., Yap, W., Zeile, P., Heinke, M., & Resch, B. (2025). [Understanding the influence of urban characteristics on cyclists’ stress measured through wearable sensors: A quantitative open data approach](https://doi.org/10.1177/23998083251394426). Environment and Planning B: Urban Analytics and City Science, 0(0). \[[pdf](https://journals.sagepub.com/doi/reader/10.1177/23998083251394426)\]

### 2023

Mameri, D., Hayes, D. S., Führer, S., Fauchery, E., Schmutz, S., Monserat, A., Hasler, T., **_Graf, D. R. M._**, Santos, J. M., Ferreira, M. T., Auer, S. [Cold thermopeaking-induced drift of nase Chondrostoma nasus larvae](https://doi.org/10.1007/s00027-023-00955-x). Aquatic Sciences 85(56) (2023). [[pdf](https://link.springer.com/content/pdf/10.1007/s00027-023-00955-x.pdf)]

<center><hr style="width:50%"></center>

Hayes, D. S., Auer, S., Fauchery, E., **_Graf, D. R. M._**, Hasler, T., Mameri, D., Schmutz, S., & Führer, S. [The interactive effect of river bank morphology and daytime on downstream displacement and stranding of cyprinid larvae in hydropeaking conditions](https://doi.org/10.1016/j.ecohyd.2022.12.001). Ecohydrology & Hydrobiology, 23(1), 152–161 (2023). [[pdf]](https://www.sciencedirect.com/science/article/pii/S1642359322000805/pdfft?md5=aa8bf9e46c379e89199c6d00ae3f59ab&pid=1-s2.0-S1642359322000805-main.pdf)

<center><hr style="width:50%"></center>

Führer, S., Hayes, D. S., Hasler, T., **_Graf, D. R. M._**, Fauchery, E., Mameri, D., Schmutz, S., & Auer, S. (2022). [Stranding of larval nase ( _Chondrostoma nasus_ L.) depending on bank slope, down-ramping rate and daytime](https://doi.org/10.3389/fenvs.2022.966418). Frontiers in Environmental Science, 10, 966418 (2023). [[pdf]](https://www.frontiersin.org/journals/environmental-science/articles/10.3389/fenvs.2022.966418/pdf)
